name: Test Examples 
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Run example Threaded
        run: cd ${GITHUB_WORKSPACE}/examples/multithreaded && chmod +x ./runme.sh && ./runme.sh
      - name: Run example Forked
        run: cd ${GITHUB_WORKSPACE}/examples/forked && chmod +x ./runme.sh && ./runme.sh
      - name: Run example Forky
        run: cd ${GITHUB_WORKSPACE}/examples/forky && chmod +x ./runme.sh && ./runme.sh
      - name: Run example Crackme
        run: cd ${GITHUB_WORKSPACE}/examples/2018_angstrom_product_key && chmod +x ./runme.sh && ./runme.sh
